{% set name = "google-cloud-kms" %}
{% set version = "1.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef62aba9f91d590755815e3e701aa5b09f507ee9b7a0acce087f5c427fe1649e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - python >=2.7,<2.8|>=3.5
    - pip
  run:
    - python >=2.7,<2.8|>=3.5
    - google-api-core
    - google-api-core-grpc
    - google-auth
    - grpc-google-iam-v1

test:
  imports:
    - google
    - google.cloud
    - google.cloud.kms_v1
    - google.cloud.kms_v1.gapic
    - google.cloud.kms_v1.gapic.transports
    - google.cloud.kms_v1.proto

about:
  home: https://github.com/GoogleCloudPlatform/google-cloud-python
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Cloud Key Management Service (KMS) API client library
  doc_url: https://cloud.google.com/kms/docs/
  dev_url: https://github.com/googleapis/google-cloud-python/tree/master/kms/google/cloud/kms_v1

extra:
  recipe-maintainers:
    - travisbickle84
